epoch: 0, train_loss:1.3968, val_accuracy: 0.7461
epoch: 1, train_loss:0.8313, val_accuracy: 0.7609
epoch: 2, train_loss:0.6987, val_accuracy: 0.7819
epoch: 3, train_loss:0.6472, val_accuracy: 0.7762
epoch: 4, train_loss:0.6242, val_accuracy: 0.7966
test_accuracy: 0.7826
epoch: 0, train_loss:1.3969, val_accuracy: 0.7232
epoch: 1, train_loss:0.8278, val_accuracy: 0.7680
epoch: 2, train_loss:0.7035, val_accuracy: 0.7786
epoch: 3, train_loss:0.6546, val_accuracy: 0.7931
epoch: 4, train_loss:0.6307, val_accuracy: 0.7871
test_accuracy: 0.7781
5
5
Epoch 0:
  Train Loss: 1.9889
  Val Accuracy: 0.6139
  Sample Activations[-1]: [0.17403618 0.22031795 0.06140364 0.25809285 0.06715271]
5
5
5
5
{'Learning_rate': 0.01, 'epochs': 5, 'batch_size': 32, 'layer_size': [784, 128, 64, 10]}
{'Learning_rate': 0.01, 'epochs': 5, 'batch_size': 32, 'layer_size': [784, 128, 64, 10]}
{'Learning_rate': 0.01, 'epochs': 5, 'batch_size': 32, 'layer_size': [784, 128, 64, 10]}
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: wandb in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (0.19.7)
Requirement already satisfied: click!=8.0.0,>=7.1 in c:\anaconda3\lib\site-packages (from wandb) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in c:\anaconda3\lib\site-packages (from wandb) (3.1.43)
Requirement already satisfied: platformdirs in c:\anaconda3\lib\site-packages (from wandb) (3.10.0)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<6,>=3.19.0 in c:\anaconda3\lib\site-packages (from wandb) (4.25.3)
Requirement already satisfied: psutil>=5.0.0 in c:\anaconda3\lib\site-packages (from wandb) (5.9.0)
Requirement already satisfied: pydantic<3,>=2.6 in c:\anaconda3\lib\site-packages (from wandb) (2.8.2)
Requirement already satisfied: pyyaml in c:\anaconda3\lib\site-packages (from wandb) (6.0.1)
Requirement already satisfied: requests<3,>=2.0.0 in c:\anaconda3\lib\site-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=2.0.0 in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (from wandb) (2.22.0)
Requirement already satisfied: setproctitle in c:\users\ashutosh patidar\appdata\roaming\python\python312\site-packages (from wandb) (1.3.5)
Requirement already satisfied: setuptools in c:\anaconda3\lib\site-packages (from wandb) (75.1.0)
Requirement already satisfied: colorama in c:\anaconda3\lib\site-packages (from click!=8.0.0,>=7.1->wandb) (0.4.6)
Requirement already satisfied: six>=1.4.0 in c:\anaconda3\lib\site-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\anaconda3\lib\site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.7)
Requirement already satisfied: annotated-types>=0.4.0 in c:\anaconda3\lib\site-packages (from pydantic<3,>=2.6->wandb) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\anaconda3\lib\site-packages (from pydantic<3,>=2.6->wandb) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in c:\anaconda3\lib\site-packages (from pydantic<3,>=2.6->wandb) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (3.7)
wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests<3,>=2.0.0->wandb) (2024.8.30)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (4.0.0)
