2025-03-10 23:52:46,756 INFO    MainThread:24156 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 23:52:46,757 INFO    MainThread:24156 [wandb_setup.py:_flush():67] Configure stats pid to 24156
2025-03-10 23:52:46,757 INFO    MainThread:24156 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Ashutosh Patidar\.config\wandb\settings
2025-03-10 23:52:46,757 INFO    MainThread:24156 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Ashutosh Patidar\OneDrive\Documents\GitHub\Assignment_1_Deep_Learning\wandb\settings
2025-03-10 23:52:46,757 INFO    MainThread:24156 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 23:52:46,757 INFO    MainThread:24156 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\Ashutosh Patidar\OneDrive\Documents\GitHub\Assignment_1_Deep_Learning\wandb\run-20250310_235246-4dq46svr\logs\debug.log
2025-03-10 23:52:46,758 INFO    MainThread:24156 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\Ashutosh Patidar\OneDrive\Documents\GitHub\Assignment_1_Deep_Learning\wandb\run-20250310_235246-4dq46svr\logs\debug-internal.log
2025-03-10 23:52:46,758 INFO    MainThread:24156 [wandb_init.py:init():761] calling init triggers
2025-03-10 23:52:46,758 INFO    MainThread:24156 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'wandb_project': 'experiment1', 'wandb_entity': 'da24s006-indian-institue-of-technology-madras-', 'dataset': 'fashion_mnist', 'epochs': 1, 'batch_size': 32, 'loss': 'cross_entropy', 'optimizer': 'adam', 'learning_rate': 0.001, 'momentum': 0.9, 'beta': 0.9, 'beta1': 0.9, 'beta2': 0.999, 'epsilon': 1e-08, 'weight_decay': 0.001, 'weight_init': 'Xavier', 'num_layers': 2, 'hidden_size': 128, 'activation': 'ReLU', '_wandb': {}}
2025-03-10 23:52:46,760 INFO    MainThread:24156 [wandb_init.py:init():784] starting backend
2025-03-10 23:52:46,760 INFO    MainThread:24156 [wandb_init.py:init():788] sending inform_init request
2025-03-10 23:52:46,851 INFO    MainThread:24156 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-10 23:52:46,853 INFO    MainThread:24156 [wandb_init.py:init():803] backend started and connected
2025-03-10 23:52:46,856 INFO    MainThread:24156 [wandb_init.py:init():896] updated telemetry
2025-03-10 23:52:47,460 INFO    MainThread:24156 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-10 23:52:47,904 INFO    MainThread:24156 [wandb_init.py:init():995] starting run threads in backend
2025-03-10 23:52:49,464 INFO    MainThread:24156 [wandb_run.py:_console_start():2377] atexit reg
2025-03-10 23:52:49,465 INFO    MainThread:24156 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-10 23:52:49,465 INFO    MainThread:24156 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-10 23:52:49,465 INFO    MainThread:24156 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-10 23:52:49,476 INFO    MainThread:24156 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-10 23:53:03,378 WARNING MsgRouterThr:24156 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashutosh Patidar\AppData\Roaming\Python\Python312\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-10 23:53:03,385 INFO    MsgRouterThr:24156 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
